### ISSUE TITLE
BUG ADVANCED SPAWN PROTECTION

### ISSUE THREAD

**Issue by 8tnc** [Timid-tec/Advanced-Spawn-Protection#2]
With the update on Tuesday, March 28, 2022, the plugin began to work incorrectly, causing the models to disappear
![bug](https://user-images.githubusercontent.com/78674116/160521462-e9b2b733-d459-4ae2-b819-f7f332a3c09a.png)

**Comment by Timid-tec** [comment]
I'll try and give a look at it tomorrow, thanks for the heads up :)

**Comment by Timid-tec** [comment]
@ZMatu I think the server models are the issue...the spawn protection only changes the color of the model; Not, the model itself or anything, in particular, dealing with the model.

**Comment by Timid-tec** [comment]
Figured out the issues, this was caused due to other related plugins.
